version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/employeesystem
    ports:
      - 8080:8000
    image: employee:django
    container_name: employee_container
    # command: python manage.py runserver 0.0.0.0:8000