# Generated by Django 4.2.6 on 2023-10-31 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("managesystem", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="work",
            name="indicator",
        ),
        migrations.AddField(
            model_name="work",
            name="indicator",
            field=models.ManyToManyField(to="managesystem.indicator"),
        ),
    ]
