# Generated by Django 4.2.6 on 2023-11-07 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("managesystem", "0002_alter_worktest_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worktest",
            name="employeeposition",
        ),
        migrations.RemoveField(
            model_name="worktest",
            name="maxunit",
        ),
        migrations.RemoveField(
            model_name="worktest",
            name="minunit",
        ),
        migrations.RemoveField(
            model_name="worktest",
            name="score",
        ),
        migrations.CreateModel(
            name="Deantest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveIntegerField(default=0)),
                ("minunit", models.PositiveIntegerField(default=0)),
                ("maxunit", models.PositiveIntegerField(default=0)),
                (
                    "employeeposition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="managesystem.employeetest",
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="managesystem.worktest",
                    ),
                ),
            ],
        ),
    ]
