# Generated by Django 4.2.6 on 2023-10-31 02:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("managesystem", "0002_remove_work_indicator_work_indicator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="work",
            name="unitsfordeans",
        ),
        migrations.RemoveField(
            model_name="work",
            name="unitsforemployees",
        ),
        migrations.RemoveField(
            model_name="work",
            name="unitsforlecturers",
        ),
        migrations.AddField(
            model_name="indicator",
            name="unitsfordeans",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="unitsforemployees",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="unitsforlecturers",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
