# Generated by Django 4.2.6 on 2023-10-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("managesystem", "0003_alter_employee_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="first_name",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="last_name",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
