# Generated by Django 4.2.6 on 2023-11-07 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("managesystem", "0003_remove_worktest_employeeposition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="worktest",
            name="employeeposition",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="managesystem.employeetest",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="worktest",
            name="maxunit",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="worktest",
            name="minunit",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="worktest",
            name="score",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="Deantest",
        ),
    ]
