# Generated by Django 4.2.6 on 2023-10-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("managesystem", "0004_employee_first_name_employee_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="first_name",
            field=models.CharField(editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_name",
            field=models.CharField(editable=False, max_length=30),
        ),
    ]
