# Generated by Django 4.2.6 on 2023-10-24 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("managesystem", "0005_alter_employee_first_name_alter_employee_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="last_name",
        ),
    ]
