# Generated by Django 4.2.6 on 2023-10-24 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("managesystem", "0008_savedata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedata",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="managesystem.attachment",
            ),
        ),
    ]
