# Generated by Django 4.2.6 on 2023-10-24 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("managesystem", "0009_alter_savedata_file"),
    ]

    operations = [
        migrations.DeleteModel(
            name="savedata",
        ),
    ]
