# Generated by Django 4.2.7 on 2023-11-20 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("managesystem", "0013_alter_result_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Save",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "Result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="managesystem.result",
                    ),
                ),
            ],
        ),
    ]
