# Generated by Django 4.2.6 on 2023-10-24 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("managesystem", "0016_remove_result_attachments_savedata"),
    ]

    operations = [
        migrations.RenameField(
            model_name="savedata",
            old_name="file",
            new_name="attachments",
        ),
    ]
