# Generated by Django 4.2.7 on 2023-11-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("managesystem", "0016_remove_save_result_save_description_save_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="save",
            name="employee",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
