# Generated by Django 4.2.7 on 2023-11-21 09:08

from django.db import migrations, models
import managesystem.models


class Migration(migrations.Migration):

    dependencies = [
        ("managesystem", "0017_save_employee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="save",
            name="employee",
        ),
        migrations.AddField(
            model_name="save",
            name="employee_firstname",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="save",
            name="employee_id",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="save",
            name="employee_lastname",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="result",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=managesystem.models.user_directory_path
            ),
        ),
    ]
