# Generated by Django 4.2.7 on 2023-11-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("managesystem", "0019_rename_employee_firstname_save_employee_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="save",
            old_name="employee",
            new_name="employee_firstname",
        ),
        migrations.AddField(
            model_name="save",
            name="employee_id",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="save",
            name="employee_lastname",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
