# Generated by Django 4.2.7 on 2023-11-21 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("managesystem", "0020_rename_employee_save_employee_firstname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="username",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
