# Generated by Django 4.2.7 on 2023-11-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("managesystem", "0021_alter_employee_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="profile",
            field=models.FileField(blank=True, null=True, upload_to="profile/"),
        ),
    ]
