# Generated by Django 4.2.7 on 2023-11-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("managesystem", "0022_employee_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="save",
            old_name="score",
            new_name="dean_score",
        ),
        migrations.RenameField(
            model_name="save",
            old_name="unit",
            new_name="employee_score",
        ),
        migrations.RemoveField(
            model_name="result",
            name="result",
        ),
        migrations.AddField(
            model_name="save",
            name="result",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
