# Generated by Django 4.1.12 on 2023-11-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "managesystem",
            "0028_alter_result_dean_score_alter_result_employee_score_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="save",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
