# Generated by Django 4.1.12 on 2023-11-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("managesystem", "0029_alter_save_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="save",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
